[Desktop Entry]
Name=NewSlickness-round
Type=X-GNOME-Metatheme
Comment=A very very black theme for gnome, a HUGE thank you to artist taner for providing the absolutely amazing wallpaper!!
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=NewSlickness-round
MetacityTheme=Unity_Round
IconTheme=LaGaDesk-BlackWhite-III
GtkColorScheme=fg_color:#d7d7d7,bg_color:#242424,base_color:#474747,text_color:#d7d7d7,selected_bg_color:#d7d7d7,selected_fg_color:#3d3d3d,tooltip_bg_color:#d7d7d7,tooltip_fg_color:#3d3d3d
CursorTheme=oxy-black
CursorSize=18
BackgroundImage=/usr/share/themes/SlicknesS-black/Slickness-black.jpg
