[Icon Theme]
Name=OSDark
Inherits=gnome, hicolor
Example=x-directory-normal

Directories=128x128/emotes,128x128/actions,128x128/apps,128x128/categories,128x128/devices,128x128/emblems,128x128/mimetypes,128x128/places,128x128/status,128x128/emotes,128x128/stock,48x48/stock,24x24/stock,16x16/stock

[128x128/actions]
Size=128
MinSize=16
MaxSize=128
Context=Actions
Type=Scalable

[128x128/apps]
Size=128
MinSize=16
MaxSize=128
Context=Applications
Type=Scalable

[128x128/categories]
Size=128
MinSize=16
MaxSize=128
Context=Categories
Type=Scalable

[128x128/devices]
Size=128
MinSize=16
MaxSize=128
Context=Devices
Type=Scalable

[128x128/emblems]
Size=128
MinSize=16
MaxSize=128
Context=Emblems
Type=Scalable

[128x128/emotes]
Size=128
MinSize=16
MaxSize=128
Context=Emotes
Type=Scalable

[128x128/mimetypes]
Size=128
MinSize=16
MaxSize=128
Context=MimeTypes
Type=Scalable

[128x128/places]
Size=128
MinSize=16
MaxSize=128
Context=Places
Type=Scalable

[128x128/status]
Size=128
MinSize=16
MaxSize=128
Context=Status
Type=Scalable

[128x128/stock]
Size=128
MinSize=50
MaxSize=128
Context=Stock
Type=Scalable

[48x48/stock]
Size=48
MinSize=26
MaxSize=48
Context=Stock
Type=Scalable

[24x24/stock]
Size=24
Context=Stock
Type=Fixed

[16x16/stock]
Size=16
Context=Stock
Type=Fixed